# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenDiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='gardenDiary',
        ),
    ]
