# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenDiary', '0004_auto_20161121_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='badge',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
