# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gardenDiary.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenDiary', '0006_auto_20161122_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='badge',
            field=models.ImageField(blank=True, null=True, upload_to=gardenDiary.models.upload_location),
        ),
    ]
