# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenDiary', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_field1',
        ),
        migrations.AddField(
            model_name='profile',
            name='gardenerDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
