# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenDiary', '0009_auto_20170105_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gardenerDesc',
            new_name='bio',
        ),
    ]
