# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='followingID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followingKey', to=settings.AUTH_USER_MODEL),
        ),
    ]
