# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenList', '0002_auto_20170106_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followingID',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user',
        ),
        migrations.AddField(
            model_name='following',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
